version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306

  app:
    image: hamdi20/imagespring
    ports:
       - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/test?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
